# Generated by Django 2.2.2 on 2021-08-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField(blank=True, max_length=500, null=True)),
                ('result', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
